swagger: "2.0"
info:
  description: "This is a sample server Edtech Service server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Edtech Platform"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "dynamodb.ap-southeast-1.amazonaws.com"
basePath: "/"
tags:
  - name: "Edtech Blogs Service"
    description: "Edtech Blogs Service"
  - name: "Edtech Comments"
    description: "Edtech Comments Service"
schemes:
  - "https"
  - "http"
paths:
  /v1/blogs/all:
    get:
      tags:
        - "Edtech Blogs Service"
      summary: "Find all blogs"
      description: ""
      operationId: "findAllBlogs"
      security:
        - edtech_auth:
            - "read:blogs"

  /v1/blogs/author/{author}:
    post:
      tags:
        - "Edtech Blogs Service"
      summary: "Create a blog in edtech platform"
      description: ""
      operationId: "addBlog"
      security:
        - edtech_auth:
            - "write:blogs"
            - "read:blogs"
    put:
      tags:
        - "Edtech Blogs Service"
      summary: "Update an existing blog"
      description: ""
      operationId: "updateBlog"
      security:
        - edtech_auth:
            - "write:blogs"
            - "read:blogs"

    get:
      tags:
        - "Edtech Blogs Service"
      summary: "Find blog by user account"
      description: ""
      operationId: "findBlogByUseraccount"
      security:
        - edtech_auth:
            - "read:blogs"

    delete:
      tags:
        - "Edtech Blogs Service"
      summary: "Delete all blogs by user account"
      description: ""
      operationId: "deleteBlogsByUserAccount"
      security:
        - edtech_auth:
            - "write:blogs"

  /v1/blogs//blog/{blogid}:
    get:
      tags:
        - "Edtech Blogs Service"
      summary: "Finds blog by blog id"
      description: ""
      operationId: "findBlogByBlogId"
      security:
        - edtech_auth:
            - "read:blogs"

    delete:
      tags:
        - "Edtech Blogs Service"
      summary: "Delete blog by blog id"
      description: ""
      operationId: "deleteBlogByBlogid"
      security:
        - edtech_auth:
            - "write:blogs"

  /v1/blogs/blog/{blogid}/comment:
    put:
      tags:
        - "Edtech Comments"
      summary: "Add a new comment to a blog"
      description: ""
      operationId: "addCommentToBlog"
      security:
        - edtech_auth:
            - "write:comments"

    delete:
      tags:
        - "Edtech Comments"
      summary: "Delete all comments by author name"
      description: ""
      operationId: "deleteCommentsByUserAccount"
      security:
        - edtech_auth:
            - "write:comments"

  /v1/blogs/blog/{blogid}/interaction:
    put:
      tags:
        - "Edtech Blog Interactions"
      summary: "Update interaction to a blog"
      description: ""
      operationId: "updateInteractionToBlog"
      security:
        - edtech_auth:
            - "write:blogs"
            - "read:blogs"

   
securityDefinitions:
  edtech_auth:
    type: "oauth2"
    authorizationUrl: "http://edtech.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:blogs: "modify blogs in your account"
      read:blogs: "query your blogs"
      write:comments: "modify comments in your account"
      read:comments: "query your comments"