package com.nus.edtech.blogs.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;
import java.util.Set;


@DynamoDBTable(tableName = "blog-t1")
public class ComplexBlogs {
    private String blogId;
    private String author;
    private String blogTitle;
    private String createdDate;
    private String blogText;
    private Set<String> blogTag;
    private List<Comments> comments;
    private List<Interactions> interactions;

    @DynamoDBHashKey(attributeName = "blogId")
    @DynamoDBAutoGeneratedKey
    public String getBlogId() { return blogId;}
    public void setBlogId(String blogId) { this.blogId = blogId;}

    @DynamoDBRangeKey(attributeName = "author")
    public String getAuthor() { return author;}
    public void setAuthor(String author) {this.author = author;}

    @DynamoDBAttribute(attributeName = "createdDate")
    public String getCreateDate() { return createdDate;}
    public void setCreateDate(String createdDate) {this.createdDate = createdDate;}

    @DynamoDBAttribute(attributeName="blogTitle")
    public String getBlogTitle() { return blogTitle;}
    public void setBlogTitle(String blogTitle) {this.blogTitle = blogTitle;}

    @DynamoDBAttribute(attributeName = "blogText")
    public String getBlogText() { return blogText; }
    public void setBlogText(String blogText) { this.blogText = blogText; }

    @DynamoDBAttribute(attributeName = "blogTag")
    public Set<String> getBlogTag() { return blogTag; }
    public void setBlogTag(Set<String> blogTag) { this.blogTag = blogTag; }

    @DynamoDBAttribute(attributeName = "comments")
    public List<Comments> getComments(){ return comments; }
    public void setComments(List <Comments> comments) { this.comments = comments; }

    @Override
    public String toString() {
        return "Blog [id=" + blogId + ", blogTitle=" + blogTitle + ", createDate=" + createdDate
                + ", blogText=" + blogText + ", author=" + author + ", blogTag=" + blogTag + "]";
    }

    @DynamoDBAttribute(attributeName = "interactions")
    public List<Interactions> getInteractions() { return interactions; }
    public void setInteractions(List<Interactions> interactions) { this.interactions = interactions; }


    @DynamoDBDocument
    public static class Comments {

        private String commentId;
        private String commentText;
        private String commentAuthor;

        @DynamoDBAttribute(attributeName = "commentId")
        public String getCommentId() { return commentId; }
        public void setCommentId(String commentId) { this.commentId = commentId; }

        @DynamoDBAttribute(attributeName = "commentText")
        public String getCommentText() { return commentText; }
        public void setCommentText(String commentText) { this.commentText = commentText; }

        @DynamoDBAttribute(attributeName = "commentAuthor")
        public String getCommentAuthor() { return commentAuthor; }
        public void setCommentAuthor(String commentAuthor) { this.commentAuthor = commentAuthor; }
    }

    @DynamoDBDocument
    public static class Interactions {
        private String interactionId;
        private String interactionType;
        private String interactionValue;
        private String interactionAuthor;

        @DynamoDBAttribute(attributeName = "interactionId")
        public String getInteractionId() { return interactionId; }
        public void setInteractionId(String interactionId) { this.interactionId = interactionId; }

        @DynamoDBAttribute(attributeName = "interactionType")
        public String getInteractionType() { return interactionType; }
        public void setInteractionType(String interactionType) { this.interactionType = interactionType; }

        @DynamoDBAttribute(attributeName = "interactionValue")
        public String getInteractionValue() { return interactionValue; }
        public void setInteractionValue(String interactionValue) { this.interactionValue = interactionValue; }

        @DynamoDBAttribute(attributeName = "interactionAuthor")
        public String getInteractionAuthor() { return interactionAuthor; }
        public void setInteractionAuthor(String interactionAuthor) { this.interactionAuthor = interactionAuthor; }
    }
}


